### ISSUE TITLE
Teckin SB50 bulb turns off if brightness less than 12% or 29

### ISSUE THREAD

**Issue by gadgetchnnel** [PaulAnnekov/tuyaha#12]
I raised this issue over in the Home Assistant repo ([here](https://github.com/home-assistant/home-assistant/issues/29572)) but it seems more an issue with this library than Home Assistant. When I try setting the brightness percent of a Teckin SB50 bulb to less than 12% (which maps to a brightness value of around 30) this turns the light off instead of setting the brightness. When setting the brightness directly, rather than as a percentage, the minimum it allows appears to be 29 and anything less than this will turn the light off.

Here are the examples from the HA issue:

Working example:

```
- service: light.turn_on
   data:
     entity_id: light.bedside_light
     brightness_pct: 12
```
This will set the light to the expected brightness.

Not working example:

```
- service: light.turn_on
   data:
     entity_id: light.bedside_light
     brightness_pct: 11
```
This will simply turn off the light.

If a colour is also included, as with the 

I have worked around this temporarily in my HA instance by overriding the Tuya component to map the brightness from the range of 0-255 to the range 28-255.

I don't know if this is specific to the Teckin SB50 bulbs or if it affects other Tuya bulbs
