### ISSUE TITLE
Energy metering for Kruidvat (Tuya white-label) smart plug

### ISSUE THREAD

**Issue by TheGroundZero** [PaulAnnekov/tuyaha#63]
Hi

I recently bought a smart plug at Kruidvat (https://www.kruidvat.be/nl/kruidvat-smart-plug/p/5315192).
These are white-label Tuya plugs.

In the Tuya app, I can see stats for energy consumption metering.
Sadly enough, I only have on/off capabilities in HA.

```yaml
{
    'header': {
        'code': 'SUCCESS',
        'payloadVersion': 1
    },
    'payload': {
        'devices': [{
                'data': {
                    'online': True,
                    'state': True
                },
                'dev_type': 'switch',
                'ha_type': 'switch',
                'icon': 'https://images.tuyaeu.com/smart/icon/bay1582725542891RIK5/15948948758fa912aaa21.png',
                'id': '8******************c',
                'name': 'Smart Plug'
            }
        ],
        'scenes': []
    }
}
```
